### ISSUE TITLE
SQL autocommit issue during startup of v4.1.1

### ISSUE THREAD

**Issue by gpciceri** [sebastian-raubach/germinate-server#3]
hi all,
I'm trying to setup an instance of germinate v4.1.1 and mysql using dockers (following docker-compose instructions provided).

But when I start germinate in the docker, I take an error (mysqld starts ok):

germinate | 26-Oct-2020 09:34:43.054 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.57
germinate | 26-Oct-2020 09:34:43.160 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
germinate | java.sql.SQLNonTransientConnectionException: Can''t call rollback when autocommit=true
germinate | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
germinate | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
germinate | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
germinate | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
germinate | 	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1851)

so an idea should be to pass autocommit=false in config.properties, in some manner (or to launch mysqld with a similar option).

may you please tell me if you are able to reproduce this situation, and how to fix it?

thanks a lot for your patience,
with best regards.

/gp

**Comment by sebastian-raubach** [comment]
Thanks for reporting this. It's something that we are aware of and it's nothing to be concerned about. It can safely be ignored.

Is everything else working as expected?

**Comment by gpciceri** [comment]
hi,
thanks for the quick reply, but I don't know how to expect, other errors occur - I've attached here the output 

[germieLog_20201026.log](https://github.com/germinateplatform/germinate-server/files/5438316/germieLog_20201026.log)

BTW, is there a test URL to check the setup is ok?

Thanks again, best regards
/gp

**Comment by sebastian-raubach** [comment]
That'll depend on your Docker setup. It'll be running at root level in the container you've set up using the port you chose.
It looks like the URL of Gatekeeper isn't set correctly, or, if you're not planning to use Gatekeeper, you have to set the property. `authentication.mode` to `NONE`.

**Comment by gpciceri** [comment]
indeed, no Gatekeeper planned usage. In my config.properties I set
...
#authentication.mode = <either 'SELECTIVE', 'FULL' or 'NONE'>
authentication.mode = NONE

same result.

May you be so kind to post a working (except of usernames/passwords, of course) test config.properties?

TIA
/gp

**Comment by sebastian-raubach** [comment]
Try specifically setting the following:
```
gatekeeper.url=
gatekeeper.username=
```
I'll fix this in the next release.

Here's a working config.properties from our production server, albeit with Gatekeeper:
```
database.username = <USERNAME>
database.password = <PASSWORD>
database.server  = <SERVER>
database.name    = <DATABASE>
database.port    =

germinate.client.url=https://ics.hutton.ac.uk/germinate-demo/

gatekeeper.url=https://ics.hutton.ac.uk/germinate-gatekeeper-4/api
gatekeeper.username=<GK USERNAME>
gatekeeper.password=<GK PASSWORD>
gatekeeper.registration.enabled=true
gatekeeper.registration.requires.approval=true

color.primary=
colors.charts=#00a0f1,#5ec418,#910080,#222183,#ff7c00,#c5e000,#c83831,#ff007a,#fff600
dashboard.categories=

data.directory.external=/data/germinate

data.import.mode=VERIFY

brapi.enabled=true

authentication.mode=SELECTIVE
gdpr.notification.enabled=true

comments.enabled=true
google.analytics.key=

files.delete.after.hours.async=12
files.delete.after.hours.temp=12

hidden.pages=
```

**Comment by gpciceri** [comment]
HURRAH - blanking

gatekeeper.url=
gatekeeper.username=

it works.

Now at http://localhost:9080 it shows a "Germinate Template Database" page.

I suppose we can close this issue. Thanks a lot for your patience and support.
/gp

**Comment by sebastian-raubach** [comment]
No problem at all, thanks for getting in touch and I'll incorporate the things you had issues with into the documentation and code for the next release!
