### ISSUE TITLE
Internal Server Error during import first spreadsheet of data.

### ISSUE THREAD

**Issue by gpciceri** [sebastian-raubach/germinate-server#5]
Hi all,p
sorry for the loose error description, but it's all the system says.

I'm trying to import a spreadsheet of data. In the config.properties I've specified

data.import.mode = IMPORT

server logs are in the following (along with the test spreadsheet)

[ROOT.2020-11-19.log](https://github.com/germinateplatform/germinate-server/files/5571794/ROOT.2020-11-19.log)
[localhost_access_log.2020-11-19.txt](https://github.com/germinateplatform/germinate-server/files/5571796/localhost_access_log.2020-11-19.txt)
[germplasm-mcpd.xlsx](https://github.com/germinateplatform/germinate-server/files/5571802/germplasm-mcpd.xlsx)

Any suggestion?
Thanks in advance.

/gp

**Comment by sebastian-raubach** [comment]
Can you please verify which version of the Germinate Docker you are using?

**Comment by sebastian-raubach** [comment]
(As a comment though, you're using an MCPD file but uploading it via the "genotype" tab, which isn't going to work. This is unrelated to the error cause though).

**Comment by gpciceri** [comment]
Thanks, I'm using 4.1.1 (installed a couple of days ago with docker-compose using most settings from the suggested .yml file)

/gp

**Comment by sebastian-raubach** [comment]
Would you be able to run some commands for me please?

```
docker exec -it <YOUR_DOCKER_IMAGE_NAME> bash

cd /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/

ls -l
```

And post the output here, please?

**Comment by gpciceri** [comment]
sure!
it is in the following attachment

[web-inf.20201120.txt](https://github.com/germinateplatform/germinate-server/files/5573273/web-inf.20201120.txt)


thank you
/gp

**Comment by sebastian-raubach** [comment]
Now that is weird. The error message complains about a method (`FileUtils.copyInputStreamToFile`) not being available during runtime. It's part of the Apache Commons IO library, which is included in your listing (`commons-io-2.6.jar`)...
I'll try and run a fresh setup of the 4.1.1 docker image locally and see if I can narrow it down.

**Comment by sebastian-raubach** [comment]
Ok, so I ran a completely fresh setup with Germinate 4.1.1 and Gatekeeper 4.1.1 inside a Docker compose each with their own MySQL docker image and the data upload/import works fine. I'm not sure why it isn't for you.
Can you try restarting the docker setup?

**Comment by gpciceri** [comment]
ok,
I've given,
docker-compose stop
docker-compose down
docker volume rm <GERMINATE AND MYSQL_GERMINATE VOLUMES>
docker system prune

and restarted with docker-compose up.

Same result (Internal Server Error). If you have specific commands to cleanup, my containers are named "germinate" and "mysql_germi" for germinate, "gatekeeper" and "mysql_gatek" for gatekeeper: feel free to suggest them to me. 

Thanks a lot.

**Comment by sebastian-raubach** [comment]
What OS are you running this on?
Can you try and remove the germinate container and image so that it re-downloads when you restart the docker-compose?
Are there any other error messages in the log files?

I've attached my test run configuration that works fine.
[germinate.zip](https://github.com/germinateplatform/germinate-server/files/5574075/germinate.zip)

**Comment by gpciceri** [comment]
Hi,
I'm running ubuntu 20.04 LTS. 
With the docker commands I've already given (see previous post), it re-downloaded images, for that I understand: if you have other cleanup commands feel free to suggest them to me.

I've seen the same error message: here are the new logs

[localhost_access_log.2020-11-20.txt](https://github.com/germinateplatform/germinate-server/files/5574202/localhost_access_log.2020-11-20.txt)
[ROOT.2020-11-20.log](https://github.com/germinateplatform/germinate-server/files/5574204/ROOT.2020-11-20.log)

But now I try with your very same configuration. Stay tuned.

**Comment by gpciceri** [comment]
UPDATE: cleaned up volules/containers/images and tested with your very test run configuration - the one you attached here in this issue. 

Docker downloaded all images from network and started.

THEN:

- Under gatekeeper I've added another database, the "germinate" one (of the test run configuration), and a new user with administrative privileges on it.
- From germinate, I've tried to upload mcpd data: same result.

The java runtime is downloaded along with the container, so it should not be a java issue... but why this error? 

Please let me know what have I to try.

Best Regards
/gp

**Comment by sebastian-raubach** [comment]
That's the thing I don't understand. The docker image contains the java runtime and Germinate contains all its dependencies (the ones I asked you to list here). The dependency that contains the class/method causing the error is present, so I don't see how it would not work, especially because I can run the same docker image with the same configuration here without any issues.

Is there another machine that you could try to run this on? Just to see if it makes any difference?

**Comment by gpciceri** [comment]
sure, good idea.

the ubuntu machine I'm using is a virtual one running under virtual box (running ubuntu as host) - so I could fire up another linux flavour, or ubuntu release. please let me know what distro/release you prefear.

thanks a lot.
/gp

**Comment by sebastian-raubach** [comment]
It shouldn't matter which distro or release. I'm just trying to figure out if there is some remnant of a corrupted image/container/whatever that's causing this.

**Comment by gpciceri** [comment]
IT WORKS!
a new ubuntu 20.04 LTS. a fresh docker-compose from your test run configuration. I was able to load the first sample spreadsheet of mcpd data (from github repo).

Thanks a lot very much. I close this issue.
/gp

**Comment by sebastian-raubach** [comment]
Glad it's working. Docker sometimes has its hiccups...
